apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keytab
  namespace:  {{ .Values.NAMESPACE }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"                                        
    keyvaultName: {{ .Values.KEYVAULT_NAME }}                                            
    objects:  |
      array:
        - |
          objectName: svc-app01-keytab
          objectType: secret
          objectEncoding: base64
    tenantId: {{ .Values.TENANT_ID }}
---