apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keytab
  namespace:  {{ .Values.NAMESPACE }}
spec:
  provider: azure
  secretObjects:                               
  - secretName: keytab
    type: Opaque
    data: 
    - objectName: keytab
      key: sql
  parameters:
    usePodIdentity: "true"                                        
    keyvaultName: {{ .Values.KEYVAULT_NAME }}                                            
    objects:  |
      array:
        - |
          objectName: keytab
          objectType: secret
    tenantId: {{ .Values.TENANT_ID }}
---